// Product/navigation wording, authorized by the M1 scope. Tamil requires owner review.
export const ENTRY_ENGLISH = {
  "entry.group.engineering": "Understand engineering",
  "entry.group.admission": "Understand engineering admission",
  "entry.group.choices": "Understand your choices",
  "entry.group.support": "Check support and prepare",
  "entry.group.next": "Choose your next direction",
  "entry.more": "Learn more",
  "entry.evidence": "Sources and evidence",
  "entry.continue": "Continue",
  "entry.previous": "Previous section",
  "entry.action": "Start here",
  "entry.official": "Open official information",
  "entry.review.only": "Development review only — navigation copy and integrated presentation await human review. Awareness pack V1 is frozen.",
  "entry.site": "Engineering guidance",
  "entry.purpose": "Understand your engineering options and choose what help you need next.",
  "entry.choose": "Where would you like to begin?",
  "entry.beginner": "Start from the beginning",
  "entry.beginner.description": "I know little about engineering. Help me understand my options.",
  "entry.personal": "Help with eligibility / cutoff",
  "entry.personal.description": "I already know the basics and want personal guidance.",
  "entry.counselling": "Help preparing for counselling",
  "entry.counselling.description": "I am thinking about college and course choices. Show me the available help.",
  "entry.unsure": "I'm not sure — help me begin",
  "entry.next": "What would you like to do next?",
  "entry.return": "Return and choose another direction",
  "entry.beginner.prompt": "You can start here without marks or personal details. Take time to think about what you want to understand before choosing a college.",
  "entry.beginner.further": "What would you like to understand about engineering before making a choice? You can keep reading this introduction or choose personal guidance when you are ready.",
  "entry.personal.intro": "You can use the existing detailed form to request eligibility and cutoff guidance from the information you provide. You do not need to read the beginner introduction first.",
  "entry.personal.limit": "The detailed form and its results are currently in English. It asks several questions. You can leave unknown personal answers blank or choose Unknown / unanswered.",
  "entry.personal.open": "Open the detailed form in English",
  "entry.counselling.intro": "You are looking for help with your choices. The guided choice-preparation experience is not ready yet. You can use the introduction or personal-guidance form below.",
  "entry.reference.title": "Detailed personal-guidance form · English",
  "entry.reference.context": "This form uses the configured pilot programme evidence. It does not assume your counselling round, category, quota, or branch preferences.",
  "entry.review": "Entry wording is a review preview. Tamil wording is pending human language review.",
  "entry.source": "About this introduction",
  "entry.source.description": "Based on the project's reviewed engineering-awareness introduction. This is general orientation, not current admission instructions.",
  "entry.language": "Language",
  "entry.missing": "This page is not yet available in the selected language. Choose another direction or explicitly open the English version.",
  "entry.english": "Open in English",
} as const;

export type EntrySemanticKey = keyof typeof ENTRY_ENGLISH;

export const ENTRY_TAMIL: Readonly<Record<EntrySemanticKey, string>> = {
  "entry.group.engineering": "பொறியியலைப் புரிந்துகொள்ளலாம்",
  "entry.group.admission": "பொறியியல் சேர்க்கையைப் புரிந்துகொள்ளலாம்",
  "entry.group.choices": "உங்கள் தேர்வுகளைப் புரிந்துகொள்ளலாம்",
  "entry.group.support": "உதவிகளைச் சரிபார்த்து தயாராகலாம்",
  "entry.group.next": "அடுத்த வழியைத் தேர்ந்தெடுக்கலாம்",
  "entry.more": "மேலும் தெரிந்துகொள்ள",
  "entry.evidence": "ஆதாரங்கள் மற்றும் தகவல் மூலங்கள்",
  "entry.continue": "தொடரலாம்",
  "entry.previous": "முந்தைய பகுதி",
  "entry.action": "இங்கே தொடங்கலாம்",
  "entry.official": "அதிகாரப்பூர்வ தகவலைத் திறக்கலாம்",
  "entry.review.only": "உருவாக்க மதிப்பாய்வுக்கு மட்டும் — வழிசெலுத்தல் வாசகங்களும் ஒருங்கிணைந்த காட்சியும் மனித மதிப்பாய்வுக்காகக் காத்திருக்கின்றன. விழிப்புணர்வு உள்ளடக்கம் V1 உறுதிசெய்யப்பட்டுள்ளது.",
  "entry.site": "பொறியியல் வழிகாட்டல்",
  "entry.purpose": "பொறியியல் படிப்பு வாய்ப்புகளைப் புரிந்துகொண்டு, அடுத்து உங்களுக்கு என்ன உதவி வேண்டும் என்பதைத் தேர்ந்தெடுக்கலாம்.",
  "entry.choose": "எங்கிருந்து தொடங்க விரும்புகிறீர்கள்?",
  "entry.beginner": "ஆரம்பத்திலிருந்து தெரிந்துகொள்ளலாம்",
  "entry.beginner.description": "பொறியியல் பற்றி எனக்கு அதிகம் தெரியாது. என்னென்ன வாய்ப்புகள் உள்ளன என்பதைப் புரிந்துகொள்ள உதவுங்கள்.",
  "entry.personal": "தகுதி / கட் ஆஃப் பற்றிய உதவி",
  "entry.personal.description": "அடிப்படை விஷயங்கள் தெரியும். எனது விவரங்களின் அடிப்படையில் வழிகாட்டல் வேண்டும்.",
  "entry.counselling": "கலந்தாய்வுக்குத் தயாராக உதவி",
  "entry.counselling.description": "கல்லூரி மற்றும் படிப்புத் தேர்வுகளைப் பற்றி யோசிக்கிறேன். இப்போது கிடைக்கும் உதவியைப் பார்க்கலாம்.",
  "entry.unsure": "எனக்குத் தெளிவில்லை — தொடங்க உதவுங்கள்",
  "entry.next": "அடுத்து என்ன செய்ய விரும்புகிறீர்கள்?",
  "entry.return": "திரும்பிச் சென்று வேறு வழியைத் தேர்ந்தெடுக்கலாம்",
  "entry.beginner.prompt": "மதிப்பெண்களோ தனிப்பட்ட விவரங்களோ இல்லாமல் இங்கே தொடங்கலாம். கல்லூரியைத் தேர்ந்தெடுக்கும் முன், எதைப் புரிந்துகொள்ள விரும்புகிறீர்கள் என்று நிதானமாக யோசிக்கலாம்.",
  "entry.beginner.further": "ஒரு முடிவை எடுக்கும் முன் பொறியியல் பற்றி என்ன தெரிந்துகொள்ள விரும்புகிறீர்கள்? இந்த அறிமுகத்தைத் தொடர்ந்து படிக்கலாம். தயாராக இருக்கும்போது தனிப்பட்ட வழிகாட்டலைத் தேர்ந்தெடுக்கலாம்.",
  "entry.personal.intro": "நீங்கள் அளிக்கும் விவரங்களைக் கொண்டு தகுதி மற்றும் கட் ஆஃப் வழிகாட்டலைப் பெற, ஏற்கெனவே உள்ள விரிவான படிவத்தைப் பயன்படுத்தலாம். முதலில் ஆரம்ப அறிமுகத்தைப் படிக்க வேண்டிய கட்டாயம் இல்லை.",
  "entry.personal.limit": "விரிவான படிவமும் அதன் முடிவுகளும் இப்போது ஆங்கிலத்தில் உள்ளன. அதில் பல கேள்விகள் உள்ளன. தெரியாத தனிப்பட்ட விவரங்களைக் காலியாக விடலாம் அல்லது தெரியாது / பதிலளிக்கவில்லை என்பதைத் தேர்ந்தெடுக்கலாம்.",
  "entry.personal.open": "ஆங்கிலத்தில் விரிவான படிவத்தைத் திறக்கலாம்",
  "entry.counselling.intro": "உங்கள் தேர்வுகளுக்கான உதவியைத் தேடுகிறீர்கள். தேர்வுப் பட்டியலைத் தயாரிக்க வழிகாட்டும் வசதி இன்னும் தயாராகவில்லை. கீழே உள்ள அறிமுகத்தையோ தனிப்பட்ட வழிகாட்டல் படிவத்தையோ பயன்படுத்தலாம்.",
  "entry.reference.title": "விரிவான தனிப்பட்ட வழிகாட்டல் படிவம் · ஆங்கிலம்",
  "entry.reference.context": "இந்தப் படிவம் சோதனைத் திட்டத்தில் உள்ள படிப்புத் தகவல்களைப் பயன்படுத்துகிறது. உங்கள் கலந்தாய்வுச் சுற்று, பிரிவு, ஒதுக்கீடு அல்லது பாடப்பிரிவு விருப்பங்களை இது தானாக எடுத்துக்கொள்வதில்லை.",
  "entry.review": "இந்த அறிமுகம் மனித மதிப்பாய்வுக்கான முன்னோட்டம். தமிழ் வாசகங்களின் மொழி மதிப்பாய்வு இன்னும் முடிவடையவில்லை.",
  "entry.source": "இந்த அறிமுகத்தைப் பற்றி",
  "entry.source.description": "திட்டத்தில் மதிப்பாய்வு செய்யப்பட்ட பொறியியல் அறிமுகத்தின் அடிப்படையில் அமைந்தது. இது பொதுவான அறிமுகம்; நடப்பு சேர்க்கைக்கான வழிமுறைகள் அல்ல.",
  "entry.language": "மொழி",
  "entry.missing": "தேர்ந்தெடுத்த மொழியில் இந்தப் பக்கம் இன்னும் தயாராகவில்லை. வேறு வழியைத் தேர்ந்தெடுக்கலாம் அல்லது ஆங்கிலப் பதிப்பைத் திறக்கலாம்.",
  "entry.english": "ஆங்கிலத்தில் திறக்கலாம்",
};

export const M1_ENTRY_COPY_REVIEW = {
  en: "PENDING_HUMAN_STUDENT_REVIEW",
  ta: "PENDING_HUMAN_LANGUAGE_REVIEW",
} as const;
